ydb.connection-string=${YDB_CONNECTION_STRING:grpc://localhost:2136/local}
ydb.auth.mode=anonymous
ydb.template.query-timeout=30s
ydb.transport.discovery-timeout=30s
spring.main.banner-mode=off
logging.level.root=WARN
