version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
  - package-ecosystem: gradle
    directories: ['/', '/samples/minimal']
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: maven
    directory: /samples/minimal
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
